import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={cn(inter.className, "flex flex-col min-h-screen")}>
                <Navbar />
                <div className="container flex-1 mx-auto py-4 md:px-8 lg:py-8">
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
